name: Task
description: Create a new task for the project
title: "[TASK] "
labels: []
body:
  - type: dropdown
    id: phase
    attributes:
      label: Phase
      description: Which phase does this task belong to?
      options:
        - "Phase 0: Foundation"
        - "Phase 1: World Design"
        - "Phase 2: Character Design"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Task Type
      description: What type of task is this?
      options:
        - Writing (lore, dialogue, descriptions)
        - Design (game design, system design)
        - Art (visual art, models, animations)
        - Music (music, sound effects)
        - Documentation (technical docs, guides)
        - Infrastructure (project setup, tools)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this task?
      options:
        - Critical (must complete first, blocks other work)
        - High (important, should complete soon)
        - Medium (standard priority)
        - Low (can be deferred)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the task in detail
      placeholder: What needs to be done?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this task is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      description: What artifacts will be produced?
      placeholder: List the expected outputs

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What must be completed before this task?
      placeholder: List any blocking tasks or requirements

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other relevant information
